### ISSUE TITLE
Problem with Standard Deviation

### ISSUE THREAD

**Issue by ZunaedSifat** [kunobyang/CSE_102_Lab_Tasks#1]
According to the article https://en.wikipedia.org/wiki/Standard_deviation, your code is incorrect. Please check it again.

My solution: http://ideone.com/A1Kxs8

**Comment by rebornplusplus** [comment]
(y) It's not my fault that google search betrays with me, and also my eyes :p 
Updated the code: https://github.com/kunobyang/CSE_102_Lab_Tasks/blob/master/B2/Week-6/p3.c
